# Generated by Django 4.0.6 on 2022-08-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('merchant', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('General Merchanise', 'General Merchanise'), ('General Services', 'General Services'), ('Transportation/Travel', 'Transportation/Travel'), ('Food/Dining', 'Food/Dining'), ('Entertainment', 'Entertainment'), ('Credits', 'Credits'), ('Other', 'Other')], default='Other', max_length=100)),
                ('issuer', models.CharField(choices=[('Wells Fargo', 'Wells Fargo'), ('Amex', 'Amex'), ('Discover', 'Discover')], max_length=100)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
